import { Category, Product, BoxConfig, Banner } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Подарочные наборы',
    slug: 'gift-sets',
    image_url: 'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=400&q=80',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Одиночные ягоды',
    slug: 'single',
    image_url: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Ассорти',
    slug: 'assorted',
    image_url: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=400&q=80',
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Конструктор',
    slug: 'constructor',
    image_url: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=400&q=80',
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    category_id: '1',
    name: 'Клубника в тёмном шоколаде',
    slug: 'klubnika-temny-shokolad',
    description: 'Отборная свежая клубника, покрытая тающим бельгийским тёмным шоколадом 70% какао. Идеальный баланс кислинки и горькой нотки премиального шоколада. Каждая ягода — маленький шедевр, созданный вручную нашими мастерами.',
    short_desc: '6 ягод в тёмном шоколаде, бельгийский 70% какао',
    price: 890,
    old_price: 1100,
    images: [
      'https://images.unsplash.com/photo-1582271066487-200c03e04173?w=800&q=85',
      'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=800&q=85',
      'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&q=85',
    ],
    is_active: true,
    is_featured: true,
    stock_count: 25,
    weight: '180 г',
    shelf_life: '48 часов',
    ingredients: 'Клубника, шоколад тёмный (какао 70%, масло какао, сахар), декор',
    sort_order: 1,
    created_at: new Date().toISOString(),
    rating: 4.9,
    reviews_count: 124,
    options: [
      { id: 'o1', product_id: '1', option_type: 'coating', option_name: 'Тёмный шоколад', price_modifier: 0, is_active: true },
      { id: 'o2', product_id: '1', option_type: 'coating', option_name: 'Молочный шоколад', price_modifier: 0, is_active: true },
      { id: 'o3', product_id: '1', option_type: 'coating', option_name: 'Белый шоколад', price_modifier: 100, is_active: true },
      { id: 'o4', product_id: '1', option_type: 'coating', option_name: 'Розовый шоколад', price_modifier: 150, is_active: true },
      { id: 'o5', product_id: '1', option_type: 'decor', option_name: 'Без декора', price_modifier: 0, is_active: true },
      { id: 'o6', product_id: '1', option_type: 'decor', option_name: 'Золотые блёстки', price_modifier: 50, is_active: true },
      { id: 'o7', product_id: '1', option_type: 'decor', option_name: 'Цветная посыпка', price_modifier: 50, is_active: true },
      { id: 'o8', product_id: '1', option_type: 'decor', option_name: 'Надпись', price_modifier: 200, is_active: true },
    ],
  },
  {
    id: '2',
    category_id: '1',
    name: 'Золотая коллекция',
    slug: 'zolotaya-kollekciya',
    description: 'Эксклюзивный набор из 24 ягод с золотым декором. Тёмный, молочный и белый шоколад, украшенные съедобным золотом и жемчужинами. Роскошный подарок для особого случая.',
    short_desc: '24 ягоды, три вида шоколада, золотой декор',
    price: 3200,
    images: [
      'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&q=85',
      'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=800&q=85',
    ],
    is_active: true,
    is_featured: true,
    stock_count: 10,
    weight: '750 г',
    shelf_life: '48 часов',
    ingredients: 'Клубника, шоколад (тёмный/молочный/белый), декор золотой съедобный',
    sort_order: 2,
    created_at: new Date().toISOString(),
    rating: 5.0,
    reviews_count: 89,
  },
  {
    id: '3',
    category_id: '1',
    name: 'Романтика',
    slug: 'romantika',
    description: '12 ягод клубники в розовом шоколаде с бутоном розы и атласной лентой. Создан специально для романтических вечеров и признаний в любви.',
    short_desc: '12 ягод в розовом шоколаде + живая роза',
    price: 2100,
    old_price: 2400,
    images: [
      'https://images.unsplash.com/photo-1581375321224-79da6fd32f6e?w=800&q=85',
      'https://images.unsplash.com/photo-1582271066487-200c03e04173?w=800&q=85',
    ],
    is_active: true,
    is_featured: true,
    stock_count: 15,
    weight: '380 г',
    shelf_life: '48 часов',
    ingredients: 'Клубника, шоколад розовый, роза натуральная',
    sort_order: 3,
    created_at: new Date().toISOString(),
    rating: 4.8,
    reviews_count: 67,
  },
  {
    id: '4',
    category_id: '2',
    name: 'Клубника на палочке',
    slug: 'klubnika-na-palochke',
    description: 'Одна ягода на элегантной палочке, покрытая шоколадом на выбор. Отличный вариант для угощения на мероприятии или маленького сладкого сюрприза.',
    short_desc: '1 ягода на палочке, шоколад на выбор',
    price: 180,
    images: [
      'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=800&q=85',
    ],
    is_active: true,
    is_featured: false,
    stock_count: 99,
    weight: '30 г',
    shelf_life: '24 часа',
    ingredients: 'Клубника, шоколад, палочка декоративная',
    sort_order: 4,
    created_at: new Date().toISOString(),
    rating: 4.7,
    reviews_count: 203,
  },
  {
    id: '5',
    category_id: '1',
    name: 'Белая сказка',
    slug: 'belaya-skazka',
    description: '12 ягод в белом шоколаде с малиновым велюром и жемчужным декором. Нежный, воздушный, как зимняя сказка.',
    short_desc: '12 ягод в белом шоколаде с малиновым декором',
    price: 1590,
    images: [
      'https://images.unsplash.com/photo-1605791195893-6b249c39b131?w=800&q=85',
      'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&q=85',
    ],
    is_active: true,
    is_featured: true,
    stock_count: 18,
    weight: '360 г',
    shelf_life: '48 часов',
    ingredients: 'Клубника, шоколад белый (32% масла какао), декор малиновый',
    sort_order: 5,
    created_at: new Date().toISOString(),
    rating: 4.9,
    reviews_count: 45,
  },
  {
    id: '6',
    category_id: '3',
    name: 'Ассорти «Премиум»',
    slug: 'assortie-premium',
    description: 'Микс из 6 ягод в трёх видах шоколада. Тёмный, молочный и белый — каждая ягода уникальна. Идеально для дегустации и знакомства с нашей коллекцией.',
    short_desc: '6 ягод: тёмный + молочный + белый шоколад',
    price: 950,
    images: [
      'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=800&q=85',
    ],
    is_active: true,
    is_featured: false,
    stock_count: 30,
    weight: '200 г',
    shelf_life: '48 часов',
    ingredients: 'Клубника, шоколад трёх видов',
    sort_order: 6,
    created_at: new Date().toISOString(),
    rating: 4.8,
    reviews_count: 56,
  },
];

export const mockBoxConfigs: BoxConfig[] = [
  {
    id: 'box1',
    name: 'Мини-коробка',
    capacity: 6,
    base_price: 150,
    image_url: 'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=400&q=80',
    is_active: true,
  },
  {
    id: 'box2',
    name: 'Стандарт',
    capacity: 12,
    base_price: 250,
    image_url: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=400&q=80',
    is_active: true,
  },
  {
    id: 'box3',
    name: 'Люкс',
    capacity: 24,
    base_price: 450,
    image_url: 'https://images.unsplash.com/photo-1581375321224-79da6fd32f6e?w=400&q=80',
    is_active: true,
  },
];

export const mockBanners: Banner[] = [
  {
    id: 'b1',
    title: 'Клубника в шоколаде\nручной работы',
    subtitle: 'Каждая ягода — маленький шедевр',
    image_url: 'https://images.unsplash.com/photo-1582271066487-200c03e04173?w=1200&q=90',
    link_url: '/catalog',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'b2',
    title: 'Золотая коллекция',
    subtitle: 'Для тех, кто ценит роскошь',
    image_url: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=1200&q=90',
    link_url: '/product/zolotaya-kollekciya',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'b3',
    title: 'Собери свой\nидеальный набор',
    subtitle: 'Конструктор наборов — выбери сам',
    image_url: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=1200&q=90',
    link_url: '/constructor',
    sort_order: 3,
    is_active: true,
  },
];
